echo off
set MS=%~fs1
set MSMDE=%~fs2
set MDLBIN=%MSMDE%bin\
set PATH=%PATH%;%MDLBIN%
set BMAKE_OPT=-I%MSMDE%mki
set DEFAULT_TARGET_PROCESSOR_ARCHITECTURE=x64
set DLM_NO_SIGN=1
set MSMDE_OUTPUT=%~fs3
pushd %~4
Bmake %~5