//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSTMC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSTMC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Browse {
            get {
                object obj = ResourceManager.GetObject("Browse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear Image.
        /// </summary>
        internal static string ButtonClearImageText {
            get {
                return ResourceManager.GetString("ButtonClearImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose &amp;Image.
        /// </summary>
        internal static string ChooseImageButtonText {
            get {
                return ResourceManager.GetString("ChooseImageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;4.0&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;ItemGroup&gt;
        ///    &lt;Filter Include=&quot;Source Files&quot;&gt;
        ///      &lt;UniqueIdentifier&gt;$guid1$&lt;/UniqueIdentifier&gt;
        ///      &lt;Extensions&gt;cpp;c;cc;cxx;def;odl;idl;hpj;bat;asm;asmx&lt;/Extensions&gt;
        ///    &lt;/Filter&gt;
        ///    &lt;Filter Include=&quot;Header Files&quot;&gt;      &lt;UniqueIdentifier&gt;$guid2$&lt;/UniqueIdentifier&gt;
        ///      &lt;Extensions&gt;h;hh;hpp;hxx;hm;inl;inc;xsd&lt;/Extensions&gt;
        ///    &lt;/Filter&gt;
        ///    &lt;Filter Include=&quot;Resour [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CONNECTFilters {
            get {
                return ResourceManager.GetString("CONNECTFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #--------------------------------------------------------------------------------------
        ///#
        ///#     $Source: MstnExamples/Annotations/incrementTextTool/incrementText.mke $
        ///#
        ///#  $Copyright: (c) 2015 Bentley Systems, Incorporated. All rights reserved. $
        ///#
        ///#--------------------------------------------------------------------------------------
        ///
        ///PolicyFile = MicroStationPolicy.mki
        ///appName         = $projectAppName$
        ///sAppName        = $projectsAppName$
        ///
        ///baseDir         = $(_MakeFilePath)
        ///privateInc      = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CONNECTmke {
            get {
                return ResourceManager.GetString("CONNECTmke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;14.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;ImportGroup Label=&quot;PropertySheets&quot; /&gt;
        ///  &lt;PropertyGroup Label=&quot;UserMacros&quot;&gt;
        ///    &lt;MSCEPath&gt;$(registry:HKEY_CURRENT_USER\Environment@MSCEPath)&lt;/MSCEPath&gt;
        ///    &lt;MSCESDKPath&gt;$(registry:HKEY_CURRENT_USER\Environment@MSCESDKPath)&lt;/MSCESDKPath&gt;
        ///  &lt;/PropertyGroup&gt;
        ///  &lt;ItemGroup Label=&quot;ProjectConfigurations&quot;&gt;
        ///    &lt;ProjectConfiguration Include=&quot;Debug|x64&quot;&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CONNECTvcproj {
            get {
                return ResourceManager.GetString("CONNECTvcproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FolderOpen {
            get {
                object obj = ResourceManager.GetObject("FolderOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LockedPadlock {
            get {
                object obj = ResourceManager.GetObject("LockedPadlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MessageCaption {
            get {
                return ResourceManager.GetString("MessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Cancel to cancel this activation.  OK to continue.
        /// </summary>
        internal static string MessageOnActivateEntered {
            get {
                return ResourceManager.GetString("MessageOnActivateEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In OnApply.
        /// </summary>
        internal static string MessageOnApply {
            get {
                return ResourceManager.GetString("MessageOnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Cancel to cancel this OnApply.  OK to continue.
        /// </summary>
        internal static string MessageOnApplyEntered {
            get {
                return ResourceManager.GetString("MessageOnApplyEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnClosed.
        /// </summary>
        internal static string MessageOnClosed {
            get {
                return ResourceManager.GetString("MessageOnClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Cancel to cancel this deactivation.  OK to continue.
        /// </summary>
        internal static string MessageOnDeactivateEntered {
            get {
                return ResourceManager.GetString("MessageOnDeactivateEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MicroStation {
            get {
                object obj = ResourceManager.GetObject("MicroStation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenedPadlock {
            get {
                object obj = ResourceManager.GetObject("OpenedPadlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OptionsPageImage {
            get {
                object obj = ResourceManager.GetObject("OptionsPageImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
